// Mocks generated by Mockito 5.4.6 from annotations
// in expenses/test/parsers/transaction_csv_parser_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:expenses/src/features/transactions/application/categorization_service.dart'
    as _i2;
import 'package:expenses/src/features/transactions/data/user_rules_repository.dart'
    as _i5;
import 'package:expenses/src/features/transactions/domain/category.dart' as _i3;
import 'package:expenses/src/features/transactions/domain/subcategory.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CategorizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategorizationService extends _i1.Mock
    implements _i2.CategorizationService {
  @override
  (_i3.Category, _i4.Subcategory) categorize(
    String? description,
    double? amount,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#categorize, [description, amount, date]),
            returnValue: (_i3.Category.housing, _i4.Subcategory.brfFee),
            returnValueForMissingStub: (
              _i3.Category.housing,
              _i4.Subcategory.brfFee,
            ),
          )
          as (_i3.Category, _i4.Subcategory));
}

/// A class which mocks [UserRulesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRulesRepository extends _i1.Mock
    implements _i5.UserRulesRepository {
  @override
  void load() => super.noSuchMethod(
    Invocation.method(#load, []),
    returnValueForMissingStub: null,
  );

  @override
  (_i3.Category, _i4.Subcategory)? getOverride(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#getOverride, [transactionId]),
            returnValueForMissingStub: null,
          )
          as (_i3.Category, _i4.Subcategory)?);

  @override
  (_i3.Category, _i4.Subcategory)? getRule(String? description) =>
      (super.noSuchMethod(
            Invocation.method(#getRule, [description]),
            returnValueForMissingStub: null,
          )
          as (_i3.Category, _i4.Subcategory)?);

  @override
  Map<String, (_i3.Category, _i4.Subcategory)> getAllRules() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRules, []),
            returnValue: <String, (_i3.Category, _i4.Subcategory)>{},
            returnValueForMissingStub:
                <String, (_i3.Category, _i4.Subcategory)>{},
          )
          as Map<String, (_i3.Category, _i4.Subcategory)>);

  @override
  Map<String, (_i3.Category, _i4.Subcategory)> getAllOverrides() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOverrides, []),
            returnValue: <String, (_i3.Category, _i4.Subcategory)>{},
            returnValueForMissingStub:
                <String, (_i3.Category, _i4.Subcategory)>{},
          )
          as Map<String, (_i3.Category, _i4.Subcategory)>);

  @override
  _i6.Future<void> addOverride(
    String? transactionId,
    _i3.Category? category,
    _i4.Subcategory? subcategory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addOverride, [
              transactionId,
              category,
              subcategory,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addRule(
    String? keyword,
    _i3.Category? category,
    _i4.Subcategory? subcategory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addRule, [keyword, category, subcategory]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeRule(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#removeRule, [keyword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
